### ISSUE TITLE
Testing 3

### ISSUE THREAD

**Issue by RRJohnso2** [drpresq/cacsupport#3]
Notes to be included:

**Comment by drpresq** [comment]
Please update issue with encountered errors.

**Comment by RRJohnso2** [comment]
During base hash, errors recieved: 

find: paths must precede expression: `opensc-0.21.0.tar.gz'
find: possible unquoted pattern after predicate `-iname'?
bash: ./bootstrap: No such file or directory
bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by RRJohnso2** [comment]
I noticed this error as well:

Command 'certutil' not found, but can be installed with:

apt install libnss3-tools

**Comment by drpresq** [comment]
Yes, that package is installed via the 'base' script prior it building open-sc (the error you got originally).

**Comment by drpresq** [comment]
> find: paths must precede expression: `opensc-0.21.0.tar.gz' find: possible unquoted pattern after predicate `-iname'?

Fixed by commit [2a265](https://github.com/drpresq/cacsupport/commit/2a2650932cb60adebeccf19773dea2ad985bb724)

Please retest. @RRJohnso2

**Comment by drpresq** [comment]
Before running please ensure you pull the updates using 
```
git pull
```
from inside the cacsupport directory

**Comment by drpresq** [comment]
Issue consolidated into issue #6
